services:
  docs:
    image: django_template_local_docs
    container_name: django_template_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_template:/app/django_template:z
    ports:
      - '9000:9000'
    command: /start-docs

  mkdocs:
    image: django_template_mkdocs
    container_name: django_template_mkdocs
    build:
      context: .
      dockerfile: ./compose/local/mkdocs_docs/Dockerfile
    volumes:
      - ./mkdocs_docs:/docs:z   # mount your MkDocs repo folder
    ports:
      - "8030:8000"
    command: serve -a 0.0.0.0:8000
