# Generated by Django 5.2.6 on 2025-10-08 15:24

import django.contrib.postgres.fields
import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Demo Category',
                'verbose_name_plural': 'Demo Categories',
            },
        ),
        migrations.CreateModel(
            name='UnfoldDemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtitle')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Rating')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='Publish Date')),
                ('publish_time', models.TimeField(blank=True, null=True, verbose_name='Publish Time')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Reviewed')),
                ('attachment', models.FileField(blank=True, upload_to='uploads/demo/', verbose_name='Attachment')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('location', location_field.models.plain.PlainLocationField(help_text='Pick the location on the map or enter the address.', max_length=63, verbose_name='Location')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.democategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Unfold Demo Model',
                'verbose_name_plural': 'Unfold Demo Models',
                'ordering': ['title'],
            },
        ),
    ]
