# Generated by Django 5.2.6 on 2025-10-09 10:02

import django.contrib.postgres.fields
import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='address',
            field=models.CharField(blank=True, help_text='Address text used as reference for map location.', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment stored under uploads/demo/.', upload_to='uploads/demo/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Associated category selected from DemoCategory.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.democategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='content',
            field=models.TextField(blank=True, help_text='Main body text supporting formatting through Unfolds WYSIWYG editor.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is currently active.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last review of this record.', null=True, verbose_name='Last Reviewed'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='location',
            field=location_field.models.plain.PlainLocationField(help_text='Interactive map field linked to the address input.', max_length=63, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional JSON metadata for storing arbitrary structured data.', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='publish_time',
            field=models.TimeField(blank=True, help_text='Time of day when the record becomes active.', null=True, verbose_name='Publish Time'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='published_on',
            field=models.DateField(blank=True, help_text='Date on which the record was or will be published.', null=True, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Optional decimal rating for evaluation purposes.', max_digits=4, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published')], default='draft', help_text='Publication status of this record.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle providing additional context.', max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of keyword tags (requires PostgreSQL backend).', size=None, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='unfolddemomodel',
            name='title',
            field=models.CharField(help_text='Primary title of the record, displayed in admin listings.', max_length=200, verbose_name='Title'),
        ),
    ]
